### ISSUE TITLE
If build is used in docker-compose then image: can be omitted

### ISSUE THREAD

**Issue by 030** [cypress-io/cypress-example-docker-compose#8]
If `build:` is used in docker-compose then `image:` can be omitted

**Comment by bahmutov** [comment]
You mean
```
services:
  web:
    image: apache
    build: ./webapp
	...
  e2e:
    image: cypress
    build: ./e2e
```

`image` is Docker image, and `build` if the folder, no?
